name: Build Workflow
on:
    push:
        branches:
            - '*'
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install
              run: npm install
            - name: Lint
              run: npm run lint
            - name: Build
              run: npm run build
            - name: Test
              run: npm test
